### ISSUE TITLE
Update to use new Gmail "Basic" URL

### ISSUE THREAD

**Issue by codepoet80** [JohnSpahr/PreMail#1]
See discussion here:
https://forums.weboslives.eu/d/34-getting-gmail-working-in-2023/3

**Comment by JohnSpahr** [comment]
Thanks codepoet! Any chance you could make a PR and compile it? I don't have time these days to get the SDK set up again

**Comment by JohnSpahr** [comment]
It looks like basic Gmail will disappear any day now, so I’ll probably just archive the repository :(
